[Paths]
# Pfad zur Highscore-Datei vom Raspberry Pi.
# Beispiel (lokal oder gemapptes Netzlaufwerk):
# Windows: Z:/highscore.json
# Linux: /home/pi/shooting/savegames/highscore.json
highscore_file = ./highscore.json

# Pfad zur Datei für die Match-Vorbereitung.
# Diese Datei wird vom Meisterschaftstool geschrieben und vom Pi gelesen.
# Beispiel:
# Windows: Z:/next_match.csv
# Linux: /home/pi/shooting/savegames/next_match.csv
next_match_file = ./next_match.csv

# Pfad zum Live-Ticker
live_ticker_file = Y:\live_match.json

[Messages]
# Jede neue Zeile muss eingerückt sein!
templates =
    📸 Nutzt die WhatsApp-Gruppe für Eure Fotos! 📲
    🏁 Gruppenphase beendet! K.O.-Start um 16:00 Uhr! 🏆
    📢 ACHTUNG: Kurze Unterbrechung - Alle zum Beamer! 📢
    🍺 Kurze Pause, gleich geht es weiter!
    🔥 Ruhe bitte! K.O.-Match läuft! 🔥

[BeamerTexte]
# Haupttext (Verwende \n für Zeilenumbrüche) und Subtext für jede Phase
NICHT_GESTARTET_HAUPT = Turnier startet\nin Kürze! ⏳
NICHT_GESTARTET_SUB = TEILNEHMER MACHT EUCH BEREIT
GRUPPEN_ABGESCHLOSSEN_HAUPT = Gruppenphase\nbeendet! ⏳
GRUPPEN_ABGESCHLOSSEN_SUB = WARTE AUF K.O.-PHASE...
GRUPPENPHASE_HAUPT = Warte auf\nnächstes Match...
GRUPPENPHASE_SUB = 
KO_PHASE_HAUPT = Warte auf\nnächstes Match...
KO_PHASE_SUB =

[MatchNamen]
VF = Viertelfinale
HF = Halbfinale
3PL = Spiel um Platz 3
FIN = Finale

#[Settings]
# Optionaler Skalierungsfaktor (z.B. 1.0 für 4K, 0.558 für 1080p)
# Wenn die Zeile fehlt oder auskommentiert ist, arbeitet die Automatik.
#manual_scale = 0.65